# Basic Project Information
sonar.projectKey=ems-app
sonar.projectName=ems-app
sonar.sourceEncoding=UTF-8

# Where the main application code is located (the current root directory)
sonar.sources=.

# Tell SonarQube exactly where Jenkins saved the coverage report
sonar.python.coverage.reportPaths=coverage.xml

# EXCLUSIONS: Tell SonarQube NOT to scan these folders for bugs
# We don't want it scanning the virtual environment or our test files
sonar.exclusions=venv/**, test_app.py, coverage.xml
